config {
    type: "view",
    schema: "standard",
    description: "Tabela contendo a lista de produtos da loja e suas categorias",
    tags: ['dooca']
}

SELECT 
  CAST (prod.id AS STRING) AS product_id,
  prod.name AS product_name,
  CAST (cat.id AS STRING) AS category_id,
  cat.name AS category_name,
FROM
  ${ref("raw_dooca_Products")} prod
JOIN
  ${ref("raw_dooca_Categories")} cat
ON
  prod.category_default_id = cat.id


