config {
    description: "Padronização da tabela de produtos",
    schema: "standard",
    type: "view",
    columns: {
        product_id: "Identificador único para a categoria - string ",
        product_name: "Nome do produto - string ",
        category_id: "Identificador da categoria do produto",
        product_sku: "Sku do produto"
    },
    tags: ['magento']
}

SELECT 
  SAFE_CAST (id AS STRING) AS product_id, 
  SAFE_CAST (name AS STRING) AS product_name,
  SAFE_CAST (2 AS STRING) AS category_id, -- #### TEMP - PROBLEMA
FROM
  ${ref("raw_magento_Products")}
