config {
    type: "view",
    schema: "staging",
    description: "All customers, with Recency, frequency  and monetary",
    tags: ['1-general']
}

SELECT
  customer.customer_id,
  customer.name,
  customer.email,
  customer.phone,
  COUNT (DISTINCT order_id) as frequency,
  DATETIME_DIFF(CURRENT_DATETIME(), MAX (creation_date),  DAY) As recency,
  SUM (value.total) AS monetary
FROM
  ${ref("orders")} O
WHERE
  status_type_category = 'Aprovado'
GROUP BY 1, 2, 3, 4

